import './global.css';
import {Providers} from "./providers";

export const metadata = {
  title: 'Welcome to nomad-ui',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
      <Providers>
        {/*<Navigation />*/}
        <main>
          <div>
            {children}
          </div>
        </main>
      </Providers>
      </body>
    </html>
  );
}
